apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    seldon-app: rest-seldon-model
  name: rest-seldon-model
spec:
  endpoints:
  - interval: 30s
    path: /prometheus
    port: http
  selector:
    matchLabels:
      seldon-app: rest-seldon-model
