apiVersion: v1
kind: Service
metadata:
  labels:
    seldon-app: seldon-model-example-classifier
  name: seldon-model-example-classifier-metrics
spec:
  ports:
  - name: metrics
    port: 6000
    protocol: TCP
    targetPort: 6000
  selector:
    seldon-app: seldon-model-example
  sessionAffinity: None
  type: ClusterIP